name: DEPLOY
on:
  push:
    branches:
    - main
  pull_request:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: .
        remote_path: /home/sulaxshayan/laravel
        remote_host: 54.66.70.26
        remote_port: 22
        remote_user: sulaxshayan
        remote_key: ${{ secrets.DEPLOY_KEY }}
        
    - name : update 
      run: |
        sudo apt update &&
        sudo apt install software-properties-common &&
        sudo add-apt-repository ppa:ondrej/php &&
        sudo apt install php &&
        sudo apt install composer &&
        sudo apt install python3-certbot-apache
     
    - name: Install Nginx
      run: |
        sudo apt install nginx -y
    - name: Start Nginx
      run: |
        sudo systemctl start nginx
    - name: Copy env file
      run: |
        echo "$(pwd)"
        cp .env.example .env
    - name:  Install Composer dependencies
      run: |
       php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
       php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
       php composer-setup.php 
       php -r "unlink('composer-setup.php');"
       sudo mv /home/sulaxshayan/laravel/composer.phar /usr/bin/composer
                                                
    #- name: Generate application key
     # run: php artisan key:generate
    
    #- name: Migrate database
     # run: php artisan migrate --force
      
    #- name: Serve Laravel Application
     # run: php artisan serve
