name: DEPLOY
on:
  push:
    branches:
    - main
  pull_request:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: .
        remote_path: /home/sulaxshayan/sample
        remote_host: 54.66.70.26
        remote_port: 22
        remote_user: sulaxshayan
        remote_key: ${{ secrets.DEPLOY_KEY }}
        
    - name: Install Nginx
      run: |
        sudo apt-get update 
        sudo apt install nginx -y
    - name: start Nginx 
      run: |
        sudo systemctl start nginx
