name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
        
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync 

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.DEPLOY_HOST}}
          REMOTE_USER: ${{secrets.DEPLOY_USER}} 
          TARGET: ${{secrets.DEPLOY_PATH}}
        
